In [1]:
# connection of python with azure 
!pip install pandas sqlalchemy pyodbc

Requirement already satisfied: pandas in c:\users\dell\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: sqlalchemy in c:\users\dell\anaconda3\lib\site-packages (1.4.39)
Requirement already satisfied: pyodbc in c:\users\dell\anaconda3\lib\site-packages (4.0.34)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\dell\anaconda3\lib\site-packages (from sqlalchemy) (2.0.1)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [44]:
# create connection with azure sql 
import pandas as pd
import urllib
from sqlalchemy import create_engine

server = 'sales-server-rajesh01.database.windows.net'
database = 'sales-db'
username = 'azureuser'
password = 'Rajesh@123'

params = urllib.parse.quote_plus(
    f"DRIVER=ODBC Driver 18 for SQL Server;"
    f"SERVER={server};"
    f"DATABASE={database};"
    f"UID={username};"
    f"PWD={password};"
    f"Encrypt=no;"
    f"TrustServerCertificate=yes;"
    f"Connection Timeout=30;"
)

engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}",fast_executemany=True)

In [45]:
engine.connect()

In [30]:
# loading dim_customer data 
df=pd.read_csv("C:/data_science/Projects/cloud_sales_analysis/data/cleaned/dim_customer.csv")

In [31]:
df.head()

  customer_id      customer_name    segment
0    PJ-19015    Pauline Johnson   Consumer
1    RA-19885       Ruben Ausman  Corporate
2    EH-14185         Evan Henry   Consumer
3    AS-10225  Alan Schoenberger  Corporate
4    BF-11080          Bart Folk   Consumer

In [32]:
df.to_sql('dim_customer',con=engine,if_exists='append',index=False)

-1

In [53]:
# Lodading dim_product 
df=pd.read_csv("C:\data_science\Projects\cloud_sales_analysis\data\cleaned\dim_product.csv",header=None, engine="python",
              on_bad_lines="skip")
df=df.iloc[:,:5]
df.columns=["product_id","product_name","category","sub_category"]
df.head()

,product_id,product_name,category,sub_category
0,product_id,product_name,category,sub_category
1,FUR-FU-10004415,"Stacking Tray, Side-Loading, Legal, Smoke",Furniture,Furnishings
2,FUR-TA-10001086,"SAFCO PlanMaster Boards, 60w x 37-1/2d, White ...",Furniture,Tables
3,TEC-PH-10002660,Nortel Networks T7316 E Nt8 B27,Technology,Phones
4,TEC-PH-10003171,Plantronics Encore H101 Dual Earpieces Headset,Technology,Phones

In [54]:
df.to_sql("dim_product",con=engine,if_exists="append",index=False)

-1

In [39]:
df=pd.read_csv("C:\data_science\Projects\cloud_sales_analysis\data\cleaned\dim_date.csv")
df.head()

   order_date  year  month  quarter
0  2020-04-07  2020      4        2
1  2020-04-08  2020      4        2
2  2020-05-22  2020      5        2
3  2020-10-18  2020     10        4
4  2020-11-28  2020     11        4

In [40]:
df.to_sql('dim_date',con=engine,if_exists='append',index=False)

-1

In [55]:
df=pd.read_csv("C:/data_science/Projects/cloud_sales_analysis/data/cleaned/fact_sales.csv")
df.head()

,order_id,product_id,customer_id,order_date,ship_date,sales,quantity,discount,profit
0,US-2020-124023,FUR-FU-10004415,PJ-19015,2020-04-07,2020-04-10,8.96,2,0.0,2.7776
1,US-2020-118997,FUR-TA-10001086,RA-19885,2020-04-08,2020-04-12,1215.92,8,0.0,316.1392
2,US-2020-143840,TEC-PH-10002660,EH-14185,2020-05-22,2020-05-29,135.98,2,0.0,33.9950
3,US-2020-143840,TEC-PH-10003171,EH-14185,2020-05-22,2020-05-29,44.95,1,0.0,12.5860
4,US-2020-110408,FUR-CH-10003774,AS-10225,2020-10-18,2020-10-20,545.88,6,0.0,70.9644

In [56]:
df.to_sql('fact_sales',con=engine,if_exists='append',index=False)

-1